// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl7d7lrnSXWHKYtm5ZCMkgxpFTkidwszg',
    appId: '1:631945531097:web:aabfeed4c91a95ff4ef8c8',
    messagingSenderId: '631945531097',
    projectId: 'whats-6c396',
    authDomain: 'whats-6c396.firebaseapp.com',
    storageBucket: 'whats-6c396.appspot.com',
    measurementId: 'G-N81TKZD32E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCSF9DlNC-_mNF1AokQgAoQjBuQBlB8i8',
    appId: '1:631945531097:android:22155e827aa3c9534ef8c8',
    messagingSenderId: '631945531097',
    projectId: 'whats-6c396',
    storageBucket: 'whats-6c396.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXb7k_rY3iGjVAszQN6C47-tkgYTLd62k',
    appId: '1:631945531097:ios:a0b94aac6d151e8d4ef8c8',
    messagingSenderId: '631945531097',
    projectId: 'whats-6c396',
    storageBucket: 'whats-6c396.appspot.com',
    iosClientId: '631945531097-s74lk98ok0b3i739t2uep7epbcvgm0qm.apps.googleusercontent.com',
    iosBundleId: 'com.example.zewin',
  );
}
